"""Initial

Revision ID: d0d65eaf8379
Revises: f184dfd2427b
Create Date: 2021-08-27 21:21:43.339992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d65eaf8379'
down_revision = 'f184dfd2427b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
